---
aws:
  region:            eu-west-2
  instance_type:     t2.micro
  instance_image:    ami-cc7066a8
  access_key_id:     !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65383734363262633030633365616231346138333863363130323032353833353663643561663930
    3631373266336435333730356535356561343965303630310a386237646133323334396266633662
    36303736626434386431343538633334356663613864353164623132343432326237653134656536
    3038613266343234300a333233656466336133336563386564353564666330393037376438666531
    37393063623436643937316162313736316435313566613338353336313636333432
  secret_access_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    63373932373434316464633034313563643534616238613332393165626166363231336564356130
    6564616430313439636439363635623033386361313534610a356361343130366463316536356662
    64646632323039323739653534336237343335663233393333623833386664656439623462376531
    3365626130383037640a323963626361383836626539616437633264396361346530383433386131
    30333363383931396263313462343531363963623164303436343638306232336666616638613439
    3637643163376435383563663163353265373962396632366261
  ssh_key_name:      eu-west-2-engagetech
  ssh_key:           !vault |
    $ANSIBLE_VAULT;1.1;AES256
    64383833336639326331663937643031653462353738356636316437336234336434306232613836
    6162613861653336623436383239323935613630376439650a323966396161373234323934333062
    38636335396430663932303335353139623238633566366230636138613532353432353734333434
    3662643732393764630a376262633561303830633433663632363635353839613965663765353231
    32396439383734333338613363396231663835346266323565646530323039376565636538626637
    35663464346133316464613737303462616363393931343131323762663439626662386663613262
    31646432373939643033333737633061343739386331643563633038643837363033366163633665
    63633734376437623930363636653665393966613530386631633861386266656534663335653963
    61333936393338663034613635386634656230356238616233306163363734396237393262313565
    32376164323835626132343565653434616337343738663866643465353565396162383363663036
    37343133333139366261313466323062613865623963373364366630636163356532303030313663
    30633864666631313832346433313833363635346232303765383366353938626138396233376331
    31303466303563383432376130393566306430633365303932323932386134623137353139643636
    66356333366634373731333663653336666263316564326232663765363261616337326336303633
    65333639343138313535643966396339623838653263366266303334383834613038316235323135
    36663930623738353766363165373563386161343335346237643131386531653766633231336261
    30393833313836613337316266626238363266623430633634313035353661346137653631356239
    65303965326562373735626638643763393038383261356262346234383130633663383565666336
    63363731323234366166303433356234643035656630613938393464333830663138613332656666
    33366139363232353330343164633635363639303531363733393538656430363635316263343035
    33613861303066396432303531646135623065613039313030346539653333363164333965643662
    65333239323762383236316138356465646162616363363061656233623331346365633430326261
    36343736353937633430653134643066636461393637343739663630373136313134353531336538
    35656233326365666465633731346433623833366361643962643332363530373132653635616432
    63663966393462356530393036613733623632333066653962326631343037333738396331663233
    66356337656336613032363463313732316137666237633237666139396338393665616232323361
    66363662353261353037316437323361336463306437316532653234636463623362366465333233
    63636239373862616265393039333234373561373338653235646139323962373066623936333631
    62393662626664643839633937316139633131303666663335666636396663623933643430396136
    35363562663564356339396438323638653531303461356265316663653366336631356535626234
    36626335633333383936613533623134346166323232333633353662336661353436373665336436
    38663031633331393061626362383565393265383962663461663335663538643264306137643865
    34373362613938623961646333303030366465656462396539356536653631656365393632616630
    66623038646538333737623636383336336562346630383638303030383932616334336530616463
    61636132383864393338356133366564656665643932333036663631393135396564343436653138
    39313462616163383138633034613731386432663631633333663963623763616235633736633131
    31363031336165323466656162336431306361363164356665356661616565353734333636663532
    33643734626239303164376335626132356362656465353831376166646664373464653364353738
    65643833643731613835343630663333313737386530326632336637666362363933633338613630
    33383264633239613032366366656265623965326539353734306537343335626334353330646436
    35383635666437626665343538313862663332613131393866353437346465336434613737353138
    39663362343138356661343462333934396331346236636535633836613834613166326232393339
    30613865646461343131333965323236633537306233303236363635633038363936363666336365
    37613765663231653163326535643838663432613666353463343461633531376162326265653532
    37306535316430653266323530653563393938663730636437646437343638333732656161343036
    36656436653139323631623161633536313065376137646634333865383532333634653039393565
    61316566313139313334303765316163656563666139393864366264303764343732656464326336
    32303638623938636130653835373062353639346632643332643864333561356233386663386634
    30313362316330636438636663316330656266666564633062633530336361373765356163616331
    62316638343166656430663461383664323663663930636264646531346364353934346532333062
    61323836393665323538343265306661366135363363326237346331656636343934323337633132
    65303566663634326536323538343166613835663564333732336635373764313335303330366564
    38353636363637663339343066623663633234636166373439646235663861303233363661363531
    32303465613530396330613166383637336563326337303030616233323836646136303938646532
    65383932323439376337666163323265613661343662323836303335363931393535613330393035
    38373533396638326236373532633661356531363934396538663332663262386134653065376530
    32613062363439633939316331376132346564376166633062323637343666613237366433363866
    37663863353763643465306239633466356236303238616231313735333730346339333263633631
    32396634666366366430346331333431636461346166373437303033633365353132623630396535
    38346261656466373534376630346531336564366637376565653432383738353030316163613238
    37326437353139313632623237323730336465313934363039363935643233343162636561666533
    36376438313231366639643331353031353561383930306432383637306136636162636330363232
    38323831386564653232373331656431633333626161396662303234363834656434643036346533
    38666136643837633464356335353966323764323638663134303565336332633766303034306462
    62303364313866356638376532653830313531353961366135616335373435333066323461363534
    36656262623134333266323461323338316630313261376134363434346566663432396461626136
    30663734613565313135303134346266623632363738303434353664636537343431616464343530
    65623439396562353933343439613133343430333239323766636536643838653064313861626239
    61666330363264363131306434623838343734366138313633623164663630313337366134613231
    34316631343038306134396434616237306535363263663762313931613534383533626238343135
    32366666306537303261326231666162326132323236376263663365656166656235303830336330
    65666466353239393331633837663836623136653365323433643535336135646261383234363738
    32383763336566353630303034663831633631356366656533323735633961626264656265366330
    32346366383535356166656664383137316137333665633239613737383539323733333232663464
    38396161636130656135316334633038626434373734633835363430363364346334386462366134
    38316132666266313863633435396564386533653038636532346565343364643562623564616330
    34383466643233343238616639323436326236393033393263393361306238633035623739313430
    37376137366462353037626365623235376330373834376565306161303764346431323633646333
    35343861393066316233356337663466623139393534623236343366346662336362326261633934
    66613135656236343562346562656466643137346364366434383130363863653166303933343336
    30313861616132356166373530646238656632353466333833653763663832366363626232643061
    61643536303233633934313534633966646561393033636665616434363964336131383833643336
    65316636313231646162616637633439633364313936393833633730363232643539653434383434
    35383039356136323063653937336435636666613435313161323963346530646234666533393962
    30373831363666326537383363343761623230333234636339643338396432353661333837396232
    61623337313738373537333435353733356439663732396439626266343433393466323230386133
    38303739623966343237303864643638633663376365333863323335386365396564313332303430
    31663733393532363034633832663030636562663631333063613139653063346165643936623234
    32383062363435316566666231303862313231353061653239663836303065666166
